[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
flagset = "0.4.3"

sdl2 = "0.34.0"
rand = "=0.7.3"
native-tls = "0.2.10"